# Generated by Django 4.2.4 on 2023-10-20 16:45

import apps.channel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos_qty', models.IntegerField(default=0)),
                ('banner', models.CharField(blank=True, max_length=255, null=True)),
                ('theme', models.CharField(choices=[('CLARO', 'Claro'), ('OSCURO', 'Oscuro'), ('DEVICE', 'Tema del dispositivo')], default='CLARO', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paused_history', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('suscribers', models.ManyToManyField(blank=True, to='channel.channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(default='thumbnail/default/video-thumbnail.jpg', upload_to=apps.channel.models.thumbnail_directory_path)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_monetized', models.BooleanField(default=False)),
                ('is_for_everyone', models.BooleanField(default=True)),
                ('video', models.FileField(default='image_1.jpg', upload_to=apps.channel.models.video_directory_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_channel', to='channel.channel')),
                ('comments', models.ManyToManyField(blank=True, related_name='video_comments', to='channel.channel')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='videl_dislikes', to='channel.channel')),
                ('likes', models.ManyToManyField(blank=True, related_name='video_likes', to='channel.channel')),
                ('views', models.ManyToManyField(blank=True, related_name='video_views', to='channel.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='welcome_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcome_video_channel', to='channel.video'),
        ),
    ]
