# Generated by Django 4.2.5 on 2023-11-25 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='video_playlists', to='playlist.playlist'),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='video_views', to='channel.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='suscribers',
            field=models.ManyToManyField(blank=True, to='channel.channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channel',
            name='welcome_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='welcome_video_channel', to='channel.video'),
        ),
    ]
