# Generated by Django 4.2.4 on 2023-10-25 22:43

import apps.channel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_playlist_video_playlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='thumbnail',
            field=models.ImageField(default='image_1.jpg', upload_to=apps.channel.models.thumbnail_directory_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default='image_1.jpg', upload_to=apps.channel.models.thumbnail_directory_path),
        ),
    ]
