# Generated by Django 4.2.5 on 2023-11-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
