# Generated by Django 4.2.4 on 2023-10-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_playlist_thumbnail_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='playlists_qty',
            field=models.IntegerField(default=0),
        ),
    ]
