# Generated by Django 4.2.5 on 2023-11-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_alter_channel_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='channel',
            name='theme',
            field=models.CharField(choices=[('CLARO', 'Claro'), ('OSCURO', 'Oscuro'), ('DEVICE', 'Tema del dispositivo')], default='OSCURO', max_length=100),
        ),
    ]
