# Generated by Django 4.2.4 on 2023-10-26 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_channel_playlists_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='videos',
        ),
    ]
