# Generated by Django 4.2.4 on 2023-10-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
        ('channel', '0005_remove_playlist_channel_remove_playlist_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='video_playlists', to='playlist.playlist'),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
