# Generated by Django 4.2.5 on 2023-11-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='final_screens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_final_screens', to='channel.video'),
        ),
    ]
